# Generated by Django 3.0.3 on 2020-03-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('latitude', models.CharField(default=None, max_length=250, null=True)),
                ('longitude', models.CharField(default=None, max_length=250, null=True)),
                ('type', models.CharField(default=None, max_length=250, null=True)),
                ('temperature', models.FloatField(default=None, null=True)),
                ('rain_prob', models.FloatField(default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('wind_speed', models.FloatField(default=None, null=True)),
                ('wind_bearing', models.FloatField(default=None, null=True)),
                ('wind_gust', models.FloatField(default=None, null=True)),
            ],
        ),
    ]
